// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Too many properties.", Scope = "namespaceanddescendants", Target = "~N:MovieCollection.TheMovieDatabase.Models")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Too many enums.", Scope = "namespaceanddescendants", Target = "~N:MovieCollection.TheMovieDatabase.Enums")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetPosterImageUrl(System.String,MovieCollection.TheMovieDatabase.Enums.PosterSize)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetBackdropImageUrl(System.String,MovieCollection.TheMovieDatabase.Enums.BackdropSize)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetProfileImageUrl(System.String,MovieCollection.TheMovieDatabase.Enums.ProfileSize)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetStillImageUrl(System.String,MovieCollection.TheMovieDatabase.Enums.StillSize)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetLogoImageUrl(System.String,MovieCollection.TheMovieDatabase.Enums.LogoSize)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetTrendingMoviesAsync(MovieCollection.TheMovieDatabase.Enums.TimeWindow)~System.Threading.Tasks.Task{MovieCollection.TheMovieDatabase.Models.PagedResult{MovieCollection.TheMovieDatabase.Models.Movie}}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetTrendingTVShowsAsync(MovieCollection.TheMovieDatabase.Enums.TimeWindow)~System.Threading.Tasks.Task{MovieCollection.TheMovieDatabase.Models.PagedResult{MovieCollection.TheMovieDatabase.Models.TVShow}}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Service doesn't support uppercase values for this item.", Scope = "member", Target = "~M:MovieCollection.TheMovieDatabase.TheMovieDatabaseService.GetTrendingPeopleAsync(MovieCollection.TheMovieDatabase.Enums.TimeWindow)~System.Threading.Tasks.Task{MovieCollection.TheMovieDatabase.Models.PagedResult{MovieCollection.TheMovieDatabase.Models.Person}}")]
